# Generated by Django 5.0.4 on 2024-05-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbase', '0006_company_remove_question_tags_minitest_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыта ли вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('date_of_interview', models.DateTimeField(blank=True, null=True, verbose_name='Дата собеседования')),
                ('status', models.IntegerField(choices=[(1, 'Открыто'), (2, 'Собеседование'), (3, 'Отказ'), (4, 'Принято'), (5, 'Отменено пользователем')], default=1, verbose_name='Статус')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancy_application_set', to='hrbase.recruiteruser', verbose_name='Рассматривающий запрос')),
            ],
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.RemoveField(
            model_name='jobseekeruser',
            name='score',
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='minitest',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='Пользовательский тест'),
        ),
        migrations.AddField(
            model_name='minitestresult',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальность результата'),
        ),
        migrations.AddField(
            model_name='recruitercompanylink',
            name='show_in_company_list',
            field=models.BooleanField(default=True, verbose_name='Отображать в списке компании'),
        ),
        migrations.AlterField(
            model_name='jobseekeruser',
            name='level',
            field=models.IntegerField(default=1, verbose_name='"Уровень"'),
        ),
        migrations.AlterField(
            model_name='minitest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='minitest_set', to='hrbase.recruiteruser', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='minitest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='minitest_set', to='hrbase.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='minitestchoiceresult',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_choice_result_set', to='hrbase.choice', verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='minitestchoiceresult',
            name='minitest_question_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_choice_result_set', to='hrbase.minitestquestionresult', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='minitestquestionresult',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильность ответа'),
        ),
        migrations.AlterField(
            model_name='minitestquestionresult',
            name='minitest_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_question_result_set', to='hrbase.minitestresult', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='minitestquestionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_question_result_set', to='hrbase.question'),
        ),
        migrations.AlterField(
            model_name='minitestquestionresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы за вопрос'),
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='count_correct',
            field=models.IntegerField(default=0, verbose_name='Количество правильных ответов'),
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Пройден ли тест'),
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='minitest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_result_set', to='hrbase.minitest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы за тест'),
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_result_set', to='hrbase.jobseekeruser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recruitercompanylink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_link_set', to='hrbase.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='recruitercompanylink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_link_set', to='hrbase.recruiteruser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='specialitytag',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='Кодовое имя'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_set', to='hrbase.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hrbase.specialitytag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancy_application_set', to='hrbase.jobseekeruser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='vacancyrequest',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_application_set', to='hrbase.vacancy', verbose_name='Вакансия'),
        ),
    ]
