# Generated by Django 5.0.4 on 2024-05-26 17:58

import django.db.models.deletion
import hrbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbase', '0008_remove_recruitercompanylink_can_add_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hrbase.models.RandomFileName('resumes/'), verbose_name='Резюме')),
                ('filename', models.TextField()),
                ('visible', models.BooleanField(default=False, verbose_name='Показывать резюме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_document_set', to='hrbase.jobseekeruser', verbose_name='Пользователь')),
            ],
        ),
    ]
