# Generated by Django 5.0.4 on 2024-05-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbase', '0002_choice_minitest_speciality_alter_userextend_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minitestquestionresult',
            name='choices',
        ),
        migrations.AddField(
            model_name='minitestquestionresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MiniTestChoiceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrbase.choice')),
                ('minitest_question_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_choice_result_set', to='hrbase.minitestquestionresult')),
            ],
        ),
    ]
