# Generated by Django 5.0.4 on 2024-05-19 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbase', '0003_remove_minitestquestionresult_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minitestresult',
            name='count_correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minitestresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='minitestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_test_result_set', to='hrbase.jobseekeruser'),
        ),
        migrations.CreateModel(
            name='SpecialityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, verbose_name='Кодовое имя')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hrbase.specialitytag', verbose_name='Родитель')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hrbase.specialitytag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='jobseekeruser',
            name='speciality',
            field=models.ManyToManyField(blank=True, to='hrbase.specialitytag', verbose_name='Специальность'),
        ),
    ]
